In [1]:
import pandas as pd

C:\Users\sukru\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\sukru\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (

In [1]:
df = pd.read_csv('Building_Permits.csv') #skip 20 rows
df

NameError: name 'pd' is not defined

In [39]:
df = pd.read_csv('Building_Permits.csv', skiprows=20) #if you want to skip the first 'n' number of rows in the dataset, you can use skiprows
df

C:\Users\sukru\AppData\Local\Temp/ipykernel_22708/2108316325.py:1: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Building_Permits.csv', skiprows=20) #if you want to skip the first 'n' number of rows in the dataset, you can use skiprows

,M814368,8,otc alterations permit,07/28/2017,2659,001,263,Unnamed: 7,Corbett,Av,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,8.1,Castro/Upper Market,94114,"(37.761092365437214, -122.44402154957145)",1472295408612
0,M814967,8,otc alterations permit,07/31/2017,1176,068,1624,NaN,Fulton,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77640228859421, -122.44361679686382)",1472619503582
1,201708013476,8,otc alterations permit,08/01/2017,6529,010,3410,NaN,26th,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.74914175355125, -122.41849211166853)",1472727381751
2,201708013544,3,additions alterations or repairs,08/01/2017,0074,043,2150,NaN,Taylor,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Russian Hill,94133.0,"(37.802405951667645, -122.41446286561653)",147281357792
3,M816927,8,otc alterations permit,08/07/2017,0941,012,2824,NaN,Filbert,St,...,NaN,NaN,NaN,NaN,NaN,2.0,Marina,94123.0,"(37.79697456740493, -122.44615769723546)",147359384812
4,201708084249,8,otc alterations permit,08/08/2017,0542,039,1,NaN,Charlton,Ct,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.79739093461306, -122.43127133823367)",1473796372030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198875,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198876,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198877,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198878,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198879,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

# Inspect missing data

In [3]:
# Check for missing values
print(df.isna().sum())

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

In [4]:
# Percentage of missing data for each column 
percent_of_missing_data = df.isnull().sum() / len(df) * 100
percent_of_missing_data

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Number Suffix                      98.885872
Street Name                                0.000000
Street Suffix                              1.391654
Unit                                      85.178984
Unit Suffix                               99.014077
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                            51.135747
First Construction Document Date           7.514329
Structural Notification                   96.519859
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Voluntary Soft-Story Retrofit             99.982403
Fire Only Permit                          90.534439
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
TIDF Compliance                           99.998994
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Site Permit                               97.305681
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

# Drop Columns with high missing values

In [5]:
threshold = 80  # Example threshold
cols_to_drop = df.columns[(df.isnull().sum() / len(df) * 100) > threshold] #same formula again
df = df.drop(columns=cols_to_drop) 
df

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Street Suffix,Description,...,Plansets,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,St,"ground fl facade: to erect illuminated, electr...",...,2.0,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,St,remove (e) awning and associated signs.,...,2.0,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,Av,installation of separating wall,...,2.0,1.0,constr type 1,1.0,constr type 1,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,Av,repair dryrot & stucco at front of bldg.,...,2.0,5.0,wood frame (5),5.0,wood frame (5),3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,St,demolish retail/office/commercial 3-story buil...,...,2.0,3.0,constr type 3,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,Montgomery,St,street space,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,Bush,St,fire alarm upgrade ref 201704123852,...,2.0,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,Indiana,St,street space,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,Sutter,St,street space permit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,Pacific,Av,street space permit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

In [7]:
df = df.drop(['Street Number Suffix', 'Unit', 'Unit Suffix', 'Voluntary Soft-Story Retrofit', 'Fire Only Permit'], axis=1)
df

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Street Suffix,Description,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,St,"ground fl facade: to erect illuminated, electr...",...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,St,remove (e) awning and associated signs.,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,Av,installation of separating wall,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,Av,repair dryrot & stucco at front of bldg.,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,St,demolish retail/office/commercial 3-story buil...,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,Montgomery,St,street space,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,Bush,St,fire alarm upgrade ref 201704123852,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,Indiana,St,street space,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,Sutter,St,street space permit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,Pacific,Av,street space permit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

In [8]:
# Percentage of missing data for each column 
percent_of_missing_data = df.isnull().sum() / len(df) * 100
percent_of_missing_data

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Name                                0.000000
Street Suffix                              1.391654
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                            51.135747
First Construction Document Date           7.514329
Structural Notification                   96.519859
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
TIDF Compliance                           99.998994
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Site Permit                               97.305681
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [9]:
col1 = df['Plansets']
col1

0         2.0
1         2.0
2         2.0
3         2.0
4         2.0
         ...
198895    NaN
198896    2.0
198897    NaN
198898    NaN
198899    NaN
Name: Plansets, Length: 198900, dtype: float64

In [10]:
col1.mean()

1.2746501971025614

# Impute missing values

In [11]:
df['Plansets'].fillna(df['Plansets'].mean(), inplace=True) #replace missing values with the mean

In [12]:
col1_imputed = df['Plansets']
col1_imputed

0         2.00000
1         2.00000
2         2.00000
3         2.00000
4         2.00000
           ...
198895    1.27465
198896    2.00000
198897    1.27465
198898    1.27465
198899    1.27465
Name: Plansets, Length: 198900, dtype: float64

In [13]:
col1_imputed.mean()

1.2746501971025614

- It's most useful when the percentage of missing data is low. If the portion of missing data is too high, the results lack natural variation that could result in an effective model.

In [35]:
df['Neighborhoods - Analysis Boundaries'] #let's see categorical column

0           Tenderloin
1           Tenderloin
2         Russian Hill
3             Nob Hill
4           Tenderloin
              ...
198895             NaN
198896             NaN
198897             NaN
198898             NaN
198899             NaN
Name: Neighborhoods - Analysis Boundaries, Length: 198900, dtype: object

In [37]:
df['Neighborhoods - Analysis Boundaries'].fillna(df['Neighborhoods - Analysis Boundaries'].mode().iloc[0], inplace=True)
print(df['Neighborhoods - Analysis Boundaries'])

0                             Tenderloin
1                             Tenderloin
2                           Russian Hill
3                               Nob Hill
4                             Tenderloin
                       ...
198895    Financial District/South Beach
198896    Financial District/South Beach
198897    Financial District/South Beach
198898    Financial District/South Beach
198899    Financial District/South Beach
Name: Neighborhoods - Analysis Boundaries, Length: 198900, dtype: object

# Numpy time

In [24]:
import pandas as pd
import numpy as np

data = {
    'Patient_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2],  # Including a duplicate patient with ID 2
    'Name': ['Alice', 'Bob', 'Charlie', '?', 'Eve', 'Frank', 'Grace', 'Hannah', 'Isaac', 'Jack', 'Bob'],
    'Age': [25, 32, 29, 40, 22, '?', 31, 28, 30, 26, 32],  # Age for Frank is '?'
    'Blood_Pressure': [120, 180, 115, 125, '?', 180, 170, 110, 118, 190, 180],  # BP for Eve is '?', Jack's BP is higher than usual
    'Diagnosis': ['Healthy', 'Hypertension', 'Healthy', 'Healthy', 'Healthy', 'Hypertension', 'Hypertension', 'Healthy', 'Healthy', 'Hypertension', 'Hypertension']
}

df = pd.DataFrame(data)
print(df)

    Patient_ID     Name Age Blood_Pressure     Diagnosis
0            1    Alice  25            120       Healthy
1            2      Bob  32            180  Hypertension
2            3  Charlie  29            115       Healthy
3            4        ?  40            125       Healthy
4            5      Eve  22              ?       Healthy
5            6    Frank   ?            180  Hypertension
6            7    Grace  31            170  Hypertension
7            8   Hannah  28            110       Healthy
8            9    Isaac  30            118       Healthy
9           10     Jack  26            190  Hypertension
10           2      Bob  32            180  Hypertension

In [25]:
import numpy as np

df.replace('?', np.nan, inplace=True)
print(df)

    Patient_ID     Name   Age  Blood_Pressure     Diagnosis
0            1    Alice  25.0           120.0       Healthy
1            2      Bob  32.0           180.0  Hypertension
2            3  Charlie  29.0           115.0       Healthy
3            4      NaN  40.0           125.0       Healthy
4            5      Eve  22.0             NaN       Healthy
5            6    Frank   NaN           180.0  Hypertension
6            7    Grace  31.0           170.0  Hypertension
7            8   Hannah  28.0           110.0       Healthy
8            9    Isaac  30.0           118.0       Healthy
9           10     Jack  26.0           190.0  Hypertension
10           2      Bob  32.0           180.0  Hypertension

In [26]:
df.drop_duplicates(inplace=True)
print(df)

   Patient_ID     Name   Age  Blood_Pressure     Diagnosis
0           1    Alice  25.0           120.0       Healthy
1           2      Bob  32.0           180.0  Hypertension
2           3  Charlie  29.0           115.0       Healthy
3           4      NaN  40.0           125.0       Healthy
4           5      Eve  22.0             NaN       Healthy
5           6    Frank   NaN           180.0  Hypertension
6           7    Grace  31.0           170.0  Hypertension
7           8   Hannah  28.0           110.0       Healthy
8           9    Isaac  30.0           118.0       Healthy
9          10     Jack  26.0           190.0  Hypertension

In [27]:
# Check for outliers
print(df.describe())

       Patient_ID        Age  Blood_Pressure
count    10.00000   9.000000        9.000000
mean      5.50000  29.222222      145.333333
std       3.02765   5.118051       33.500000
min       1.00000  22.000000      110.000000
25%       3.25000  26.000000      118.000000
50%       5.50000  29.000000      125.000000
75%       7.75000  31.000000      180.000000
max      10.00000  40.000000      190.000000

In [28]:
# Cap Blood_Pressure at 180
df['Blood_Pressure'] = df['Blood_Pressure'].astype(float)  # Convert to float first to ensure operations work
df['Blood_Pressure'] = np.where(df['Blood_Pressure'] > 180, 180, df['Blood_Pressure'])
print(df)

   Patient_ID     Name   Age  Blood_Pressure     Diagnosis
0           1    Alice  25.0           120.0       Healthy
1           2      Bob  32.0           180.0  Hypertension
2           3  Charlie  29.0           115.0       Healthy
3           4      NaN  40.0           125.0       Healthy
4           5      Eve  22.0             NaN       Healthy
5           6    Frank   NaN           180.0  Hypertension
6           7    Grace  31.0           170.0  Hypertension
7           8   Hannah  28.0           110.0       Healthy
8           9    Isaac  30.0           118.0       Healthy
9          10     Jack  26.0           180.0  Hypertension

- WC3 examples